<?php

$defaultExecutableExtension = DIRECTORY_SEPARATOR === '\\' ? '.exe' : '';

$resolveProjectPath = static function (?string $value, string $defaultRelative): string {
    $candidate = trim((string) $value);
    $candidate = $candidate !== '' ? $candidate : $defaultRelative;

    $isAbsolute = preg_match('#^(?:[A-Za-z]:[\\\\/]|[/\\\\]{2}|/)#', $candidate) === 1;

    return $isAbsolute ? $candidate : base_path($candidate);
};

$resolveExecutablePath = static function (?string $value, string $defaultRelative) use ($resolveProjectPath): string {
    $candidate = trim((string) $value);

    if ($candidate === '') {
        return $resolveProjectPath(null, $defaultRelative);
    }

    $looksLikePath = str_contains($candidate, '/')
        || str_contains($candidate, '\\')
        || $candidate === '.'
        || str_starts_with($candidate, '.');

    if (!$looksLikePath) {
        return $candidate;
    }

    $resolved = $resolveProjectPath($candidate, $defaultRelative);
    if (is_dir($resolved)) {
        $resolved = rtrim($resolved, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . basename($defaultRelative);
    }

    return $resolved;
};

$resolvePackagePath = static function (?string $projectRelativePath, ?string $legacyStorageRelativePath) use ($resolveProjectPath): string {
    $projectRelativePath = trim((string) $projectRelativePath);
    if ($projectRelativePath !== '') {
        return $resolveProjectPath($projectRelativePath, 'storage/app/tinymist/packages');
    }

    return storage_path('app/' . trim((string) ($legacyStorageRelativePath ?: 'tinymist/packages'), '/\\'));
};

/**
 * Tinymist/Typst editor configuration options.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Typst CLI Path
    |--------------------------------------------------------------------------
    |
    | Path to typst CLI executable. Can be absolute path or command name
    | if available in system PATH.
    |
    */
    'typst_cli_path' => $resolveExecutablePath(env('TYPST_CLI_PATH'), 'vendor/bin/typst' . $defaultExecutableExtension),

    /*
    |--------------------------------------------------------------------------
    | Tinymist CLI Path
    |--------------------------------------------------------------------------
    |
    | Path to tinymist CLI executable (for LSP features).
    |
    */
    'tinymist_cli_path' => $resolveExecutablePath(env('TINYMIST_CLI_PATH'), 'vendor/bin/tinymist' . $defaultExecutableExtension),

    /*
    |--------------------------------------------------------------------------
    | Pandoc CLI Path
    |--------------------------------------------------------------------------
    |
    | Path to pandoc CLI executable (for document conversion workflows).
    |
    */
    'pandoc_cli_path' => $resolveExecutablePath(env('PANDOC_CLI_PATH'), 'vendor/bin/pandoc' . $defaultExecutableExtension),

    /*
    |--------------------------------------------------------------------------
    | Typst Package Path
    |--------------------------------------------------------------------------
    |
    | Absolute path to locally installed Typst packages. `TYPST_PACKAGE_PATH`
    | is treated as relative to the project root when not absolute.
    |
    */
    'package_path' => $resolvePackagePath(env('TYPST_PACKAGE_PATH'), env('TINYMIST_PACKAGES_STORAGE_PATH')),

    /*
    |--------------------------------------------------------------------------
    | Enable Tinymist Editor
    |--------------------------------------------------------------------------
    |
    | Enable or disable the Tinymist editor option.
    | Requires typst CLI to be installed and accessible.
    |
    */
    'enabled' => env('TINYMIST_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Compilation Timeout
    |--------------------------------------------------------------------------
    |
    | Maximum time (in seconds) to wait for typst compilation.
    |
    */
    'timeout' => env('TINYMIST_TIMEOUT', 30),

    // AJAX fallback settings
    'ajax_timeout' => env('TINYMIST_AJAX_TIMEOUT', 30),

    /*
    |--------------------------------------------------------------------------
    | Max Document Size
    |--------------------------------------------------------------------------
    |
    | Maximum size (in KB) of Typst document to compile. Used in controller.
    |
    */
    'max_document_size' => env('TINYMIST_MAX_SIZE', 1024),

    /*
    |--------------------------------------------------------------------------
    | WebSocket Token Settings
    |--------------------------------------------------------------------------
    |
    | Controls the signing key and lifespan for tokens that authenticate the
    | browser when connecting to the Tinymist file-sync WebSocket bridge.
    |
    */
    'ws_token_secret' => env('TINYMIST_WS_SECRET'),
    'ws_token_ttl' => env('TINYMIST_WS_TOKEN_TTL', 1800),

    /*
    |--------------------------------------------------------------------------
    | Typst Package Storage
    |--------------------------------------------------------------------------
    |
    | Location of installed Typst packages and the cached GitHub packages clone,
    | both relative to storage/app.
    |
    */
    'packages_storage_path' => env('TINYMIST_PACKAGES_STORAGE_PATH', 'tinymist/packages'),
    'github_packages_storage_path' => env('TINYMIST_GITHUB_PACKAGES_STORAGE_PATH', 'tinymist/github/packages'),
    'github_packages_repo' => env('TINYMIST_GITHUB_PACKAGES_REPO', 'https://github.com/typst/packages.git'),
    'github_packages_branch' => env('TINYMIST_GITHUB_PACKAGES_BRANCH', 'main'),


    /*
    |--------------------------------------------------------------------------
    | Document Storage Path
    |--------------------------------------------------------------------------
    |
    | Directory where temporary .typ files are stored for LSP processing.
    | Relative to storage/app/
    |
    */
    'document_storage_path' => 'tinymist',

];
