<?php

/**
 * Tinymist/Typst editor configuration options.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Typst CLI Path
    |--------------------------------------------------------------------------
    |
    | Path to typst CLI executable. Can be absolute path or command name
    | if available in system PATH.
    |
    */
    'typst_cli_path' => env('TYPST_CLI_PATH', base_path('vendor/bin/typst' . (DIRECTORY_SEPARATOR === '\\' ? '.exe' : ''))),

    /*
    |--------------------------------------------------------------------------
    | Tinymist CLI Path
    |--------------------------------------------------------------------------
    |
    | Path to tinymist CLI executable (for LSP features).
    |
    */
    'tinymist_cli_path' => env('TINYMIST_CLI_PATH', base_path('vendor/bin/tinymist' . (DIRECTORY_SEPARATOR === '\\' ? '.exe' : ''))),

    /*
    |--------------------------------------------------------------------------
    | Enable Tinymist Editor
    |--------------------------------------------------------------------------
    |
    | Enable or disable the Tinymist editor option.
    | Requires typst CLI to be installed and accessible.
    |
    */
    'enabled' => env('TINYMIST_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Compilation Timeout
    |--------------------------------------------------------------------------
    |
    | Maximum time (in seconds) to wait for typst compilation.
    |
    */
    'timeout' => env('TINYMIST_TIMEOUT', 30),

    // AJAX fallback settings
    'ajax_timeout' => env('TINYMIST_AJAX_TIMEOUT', 30),

    /*
    |--------------------------------------------------------------------------
    | Max Document Size
    |--------------------------------------------------------------------------
    |
    | Maximum size (in KB) of Typst document to compile.
    |
    */
    'max_document_size' => env('TINYMIST_MAX_SIZE', 1024),

    /*
    |--------------------------------------------------------------------------
    | LSP Mode
    |--------------------------------------------------------------------------
    |
    | Enable Tinymist LSP mode for incremental compilation.
    | When enabled, uses persistent LSP process instead of spawning
    | typst CLI for each compilation.
    |
    */
    'lsp_enabled' => env('TINYMIST_LSP_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | LSP Max Processes
    |--------------------------------------------------------------------------
    |
    | Maximum number of concurrent LSP processes.
    | Additional requests will be queued or fall back to typst CLI.
    |
    */
    'lsp_max_processes' => env('TINYMIST_LSP_MAX_PROCESSES', 10),

    /*
    |--------------------------------------------------------------------------
    | LSP Process Idle Timeout
    |--------------------------------------------------------------------------
    |
    | Time (in minutes) before an idle LSP process is terminated.
    | Matches draft autosave expiry time.
    |
    */
    'lsp_idle_timeout' => env('TINYMIST_LSP_IDLE_TIMEOUT', 60),

    /*
    |--------------------------------------------------------------------------
    | WebSocket Preview Server (On-Demand per Page)
    |--------------------------------------------------------------------------
    |
    | Base ports for on-demand preview servers.
    | Each page gets: control_port = base + (2 * page_id)
    |                 data_port = base + (2 * page_id) + 1
    | Example: Page ID 5 → Control: 33636, Data: 33637
    |
    */

    // Base port for Control Plane (events, status, outline)
    // Actual port = base_port + (2 * page_id)
    'control_plane_base_port' => env('TINYMIST_CONTROL_BASE_PORT', 33626),

    // Base port for Data Plane (binary SVG streaming)
    // Actual port = base_port + (2 * page_id) + 1
    'data_plane_base_port' => env('TINYMIST_DATA_BASE_PORT', 33625),

    // Preview server host
    'preview_host' => env('TINYMIST_PREVIEW_HOST', '127.0.0.1'),

    // Maximum concurrent preview servers
    'max_preview_servers' => env('TINYMIST_MAX_PREVIEW_SERVERS', 20),

    // Preview server idle timeout (minutes) before auto-termination
    'preview_idle_timeout' => env('TINYMIST_PREVIEW_IDLE_TIMEOUT', 30),


    /*
    |--------------------------------------------------------------------------
    | WebSocket Token Settings
    |--------------------------------------------------------------------------
    |
    | Controls the signing key and lifespan for tokens that authenticate the
    | browser when connecting to the Tinymist file-sync WebSocket bridge.
    |
    */
    'ws_token_secret' => env('TINYMIST_WS_SECRET'),
    'ws_token_ttl' => env('TINYMIST_WS_TOKEN_TTL', 900),

    /*
    |--------------------------------------------------------------------------
    | Typst Package Storage
    |--------------------------------------------------------------------------
    |
    | Location of installed Typst packages and the cached GitHub packages clone,
    | both relative to storage/app.
    |
    */
    'packages_storage_path' => env('TINYMIST_PACKAGES_STORAGE_PATH', 'tinymist/packages'),
    'github_packages_storage_path' => env('TINYMIST_GITHUB_PACKAGES_STORAGE_PATH', 'tinymist/github/packages'),
    'github_packages_repo' => env('TINYMIST_GITHUB_PACKAGES_REPO', 'https://github.com/typst/packages.git'),
    'github_packages_branch' => env('TINYMIST_GITHUB_PACKAGES_BRANCH', 'main'),


    /*
    |--------------------------------------------------------------------------
    | Document Storage Path
    |--------------------------------------------------------------------------
    |
    | Directory where temporary .typ files are stored for LSP processing.
    | Relative to storage/app/
    |
    */
    'document_storage_path' => 'tinymist',

];
